### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by bloodcarter** [kazeto/phillip#3]
make crashed with the following error:
src/kb.o: In function `phil::kb::knowledge_base_t::create_reachable_matrix()':
kb.cpp:(.text+0xe8ad): undefined reference to `pthread_create'
kb.cpp:(.text+0xea51): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 1

OS Ubuntu 16.10

**Comment by kazeto** [comment]
That is because the compiler failed to link the library of pthread.
Verify that -lpthread option is added on compiling and library file of pthread exists in any directory of LIBRARY_PATH.
(Since pthread is standard library, I think you should verify your command options.)

If you cannot solve the problem, let me see your Makefile.

**Comment by bloodcarter** [comment]
Thanks! Solved. I need to add not -lpthread, but -pthread.
